version: "3.8"

services:
    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8100:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app

    # Application service
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        #   - ./vendor:/var/www/vendor
        #   - ./storage:/var/www/storage
        networks:
            - laravel
        # Removed depends_on: db

# Networks for container communication
networks:
    laravel:
